// Optional browser checks: NODE_PATH=/path/to/node_modules node tests/browser_smoke.cjs [site URL]
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:8000/';
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  const total=await page.locator('.market-record').count();
  assert(total>=50);
  assert.equal(await page.locator('.market-record:visible').count(),total);
  const ranked=await page.locator('.market-record').evaluateAll(rows=>rows.map(r=>Number(r.dataset.rank)));
  assert.deepEqual(ranked,[...ranked].sort((a,b)=>a-b));
  await page.screenshot({path:'/tmp/opportunity-desktop.png',fullPage:true});
  await page.locator('#market-search').fill('JetBrains');
  assert.equal(await page.locator('.market-record:visible').count(),1);
  await page.getByRole('button',{name:'Reset',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.market-record:not([hidden])').length>=50);
  await page.locator('.advanced-filters summary').click();
  await page.locator('[data-filter="codex"]').fill('8');
  await page.locator('[data-filter="saturation"]').fill('5');
  const filtered=await page.locator('.market-record:visible').evaluateAll(rows=>rows.map(r=>({codex:Number(r.dataset.codex),saturation:Number(r.dataset.saturation)})));
  assert(filtered.length>0);assert(filtered.every(r=>r.codex>=8&&r.saturation<=5));
  await page.locator('#asymmetric-preset').click();
  assert.equal(await page.locator('.market-record:visible').count(),0);
  assert(await page.locator('#no-market-results').isVisible());
  await page.getByRole('button',{name:'Reset',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.market-record:not([hidden])').length>=50);
  await page.locator('#market-sort').selectOption('asymmetry');
  const asym=await page.locator('.market-record').evaluateAll(rows=>rows.map(r=>r.dataset.asymmetry));
  const known=asym.filter(v=>v!=='').map(Number);assert(known.length>0);
  assert.deepEqual(known,[...known].sort((a,b)=>b-a));assert(asym.slice(known.length).every(v=>v===''));
  await page.locator('nav').getByRole('link',{name:'Top Opportunities'}).click();
  assert(await page.getByRole('heading',{name:'Choose a market to investigate.'}).isVisible());
  assert.equal(await page.locator('section.panel').count(),10);
  await page.goto(new URL('marketplaces/wordpress.html',base).href);
  assert(await page.getByRole('heading',{name:'WordPress plugins',exact:true}).isVisible());
  assert(await page.locator('#entrants tbody tr').count()>0);
  await page.locator('nav').getByRole('link',{name:'Changes'}).click();
  assert.equal(await page.getByRole('heading',{name:'Baseline — insufficient historical data'}).count(),3);
  await page.locator('nav').getByRole('link',{name:'Shopify Apps'}).click();
  assert(await page.locator('.app-record').count()>=121);
  await page.locator('#app-search').fill('Melon');
  assert.equal(await page.locator('.app-record:visible').count(),1);
  await page.setViewportSize({width:390,height:844});
  const oldOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  assert(!oldOverflow,'Shopify page must fit a mobile viewport');
  await page.locator('nav').getByRole('link',{name:'Marketplaces'}).click();
  await page.screenshot({path:'/tmp/opportunity-mobile.png',fullPage:true});
  assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'Marketplace page must fit mobile viewport');
  const response=await page.request.get(new URL('data/marketplaces.json',base).href);
  assert(response.ok());assert((await response.json()).marketplaces.length>=50);
  assert.deepEqual(errors,[]);
  const offline=await browser.newContext({javaScriptEnabled:false});
  const nojs=await offline.newPage();await nojs.goto(base);
  assert(await nojs.locator('.market-record').count()>=50);
  await browser.close();
  console.log(`Browser smoke passed: ${total} marketplaces, filters, sorting, Top 10, details, history, Shopify, mobile and no-JS rendering.`);
})().catch(error=>{console.error(error);process.exit(1)});
